/**
 * Preset data for CICIDS2017 ML feature testing and initial dashboard state
 */

export const TRAFFIC_PRESETS = [
  {
    id: 'benign_http',
    name: 'Normal HTTP Web Traffic (Benign)',
    category: 'BENIGN',
    badgeColor: 'emerald',
    description: 'Standard HTTP GET request to web app endpoint',
    data: {
      _presetType: 'benign',
      Destination_Port: 80,
      Flow_Duration: 3450,
      Total_Fwd_Packets: 4,
      Total_Backward_Packets: 5,
      Total_Length_of_Fwd_Packets: 280,
      Total_Length_of_Bwd_Packets: 1250,
      Fwd_Packet_Length_Max: 140,
      Fwd_Packet_Length_Min: 40,
      Bwd_Packet_Length_Max: 500,
      Bwd_Packet_Length_Min: 60,
      Flow_Bytes_s: 443478.26,
      Flow_Packets_s: 2608.7,
      Flow_IAT_Mean: 431.25,
      SYN_Flag_Count: 1,
      ACK_Flag_Count: 5,
      Packet_Length_Mean: 170,
    }
  },
  {
    id: 'ddos_syn',
    name: 'DDoS SYN Flood Attack',
    category: 'DoS / DDoS',
    badgeColor: 'red',
    description: 'High volume rapid SYN flags flooding destination port 443',
    data: {
      _presetType: 'dos',
      Destination_Port: 443,
      Flow_Duration: 185000,
      Total_Fwd_Packets: 1450,
      Total_Backward_Packets: 2,
      Total_Length_of_Fwd_Packets: 87000,
      Total_Length_of_Bwd_Packets: 120,
      Fwd_Packet_Length_Max: 60,
      Fwd_Packet_Length_Min: 60,
      Bwd_Packet_Length_Max: 60,
      Bwd_Packet_Length_Min: 60,
      Flow_Bytes_s: 470918.9,
      Flow_Packets_s: 7848.6,
      Flow_IAT_Mean: 127.5,
      SYN_Flag_Count: 1450,
      ACK_Flag_Count: 0,
      Packet_Length_Mean: 60,
    }
  },
  {
    id: 'port_scan',
    name: 'Nmap Port Scan Reconnaissance',
    category: 'PortScan',
    badgeColor: 'amber',
    description: 'Probing open ports sequentially (22, 80, 443, 3389, 8080)',
    data: {
      _presetType: 'portscan',
      Destination_Port: 22,
      Flow_Duration: 120,
      Total_Fwd_Packets: 2,
      Total_Backward_Packets: 1,
      Total_Length_of_Fwd_Packets: 0,
      Total_Length_of_Bwd_Packets: 0,
      Fwd_Packet_Length_Max: 0,
      Fwd_Packet_Length_Min: 0,
      Bwd_Packet_Length_Max: 0,
      Bwd_Packet_Length_Min: 0,
      Flow_Bytes_s: 0,
      Flow_Packets_s: 25000,
      Flow_IAT_Mean: 60,
      SYN_Flag_Count: 2,
      ACK_Flag_Count: 0,
      Packet_Length_Mean: 0,
    }
  },
  {
    id: 'sql_injection',
    name: 'Web Attack - SQL Injection',
    category: 'Web Attack',
    badgeColor: 'rose',
    description: 'Malicious payload in URI field aiming to extract database credentials',
    data: {
      _presetType: 'sql_injection',
      Destination_Port: 80,
      Flow_Duration: 12450,
      Total_Fwd_Packets: 8,
      Total_Backward_Packets: 6,
      Total_Length_of_Fwd_Packets: 4820,
      Total_Length_of_Bwd_Packets: 340,
      Fwd_Packet_Length_Max: 1420,
      Fwd_Packet_Length_Min: 54,
      Bwd_Packet_Length_Max: 120,
      Bwd_Packet_Length_Min: 0,
      Flow_Bytes_s: 414457.8,
      Flow_Packets_s: 1124.5,
      Flow_IAT_Mean: 957.6,
      SYN_Flag_Count: 1,
      ACK_Flag_Count: 7,
      Packet_Length_Mean: 368.5,
    }
  },
  {
    id: 'brute_force',
    name: 'SSH Brute Force Dictionary Attack',
    category: 'Brute Force',
    badgeColor: 'purple',
    description: 'Repeated authentication password attempts against port 22',
    data: {
      _presetType: 'bruteforce',
      Destination_Port: 22,
      Flow_Duration: 65400,
      Total_Fwd_Packets: 42,
      Total_Backward_Packets: 38,
      Total_Length_of_Fwd_Packets: 2940,
      Total_Length_of_Bwd_Packets: 4180,
      Fwd_Packet_Length_Max: 180,
      Fwd_Packet_Length_Min: 40,
      Bwd_Packet_Length_Max: 220,
      Bwd_Packet_Length_Min: 40,
      Flow_Bytes_s: 108868.5,
      Flow_Packets_s: 1223.2,
      Flow_IAT_Mean: 817.5,
      SYN_Flag_Count: 4,
      ACK_Flag_Count: 36,
      Packet_Length_Mean: 89.0,
    }
  }
];

export const MOCK_RECENT_DETECTIONS = [
  {
    id: 'DET-98241',
    timestamp: new Date(Date.now() - 2 * 60000).toISOString(),
    sourceIp: '192.168.1.105',
    destIp: '10.0.0.4',
    destPort: 80,
    attackType: 'BENIGN',
    prediction: 0,
    confidence: 98.45,
    protocol: 'HTTP/TCP',
    status: 'Clean',
  },
  {
    id: 'DET-98240',
    timestamp: new Date(Date.now() - 7 * 60000).toISOString(),
    sourceIp: '172.16.0.42',
    destIp: '10.0.0.4',
    destPort: 443,
    attackType: 'DoS / DDoS SYN Flood',
    prediction: 1,
    confidence: 97.80,
    protocol: 'TCP SYN',
    status: 'Blocked',
  },
  {
    id: 'DET-98239',
    timestamp: new Date(Date.now() - 15 * 60000).toISOString(),
    sourceIp: '198.51.100.88',
    destIp: '10.0.0.4',
    destPort: 22,
    attackType: 'PortScan Probe',
    prediction: 1,
    confidence: 94.15,
    protocol: 'TCP SYN',
    status: 'Alerted',
  },
  {
    id: 'DET-98238',
    timestamp: new Date(Date.now() - 24 * 60000).toISOString(),
    sourceIp: '192.168.1.112',
    destIp: '10.0.0.4',
    destPort: 80,
    attackType: 'BENIGN',
    prediction: 0,
    confidence: 99.12,
    protocol: 'HTTPS/TCP',
    status: 'Clean',
  },
  {
    id: 'DET-98237',
    timestamp: new Date(Date.now() - 38 * 60000).toISOString(),
    sourceIp: '203.0.113.14',
    destIp: '10.0.0.4',
    destPort: 80,
    attackType: 'Web Attack - SQL Injection',
    prediction: 1,
    confidence: 98.75,
    protocol: 'HTTP GET',
    status: 'Mitigated',
  },
  {
    id: 'DET-98236',
    timestamp: new Date(Date.now() - 55 * 60000).toISOString(),
    sourceIp: '192.168.1.130',
    destIp: '10.0.0.4',
    destPort: 443,
    attackType: 'BENIGN',
    prediction: 0,
    confidence: 95.60,
    protocol: 'TLS v1.3',
    status: 'Clean',
  },
  {
    id: 'DET-98235',
    timestamp: new Date(Date.now() - 72 * 60000).toISOString(),
    sourceIp: '45.33.32.156',
    destIp: '10.0.0.4',
    destPort: 22,
    attackType: 'Brute Force (SSH)',
    prediction: 1,
    confidence: 92.40,
    protocol: 'SSH-2.0',
    status: 'Blocked',
  }
];

export const MOCK_TRAFFIC_TIMELINE = [
  { time: '00:00', benign: 420, attacks: 12, total: 432 },
  { time: '03:00', benign: 380, attacks: 8, total: 388 },
  { time: '06:00', benign: 520, attacks: 25, total: 545 },
  { time: '09:00', benign: 1250, attacks: 64, total: 1314 },
  { time: '12:00', benign: 1890, attacks: 142, total: 2032 },
  { time: '15:00', benign: 1640, attacks: 98, total: 1738 },
  { time: '18:00', benign: 1420, attacks: 55, total: 1475 },
  { time: '21:00', benign: 890, attacks: 31, total: 921 },
];

export const MOCK_ATTACK_DISTRIBUTION = [
  { name: 'BENIGN', value: 8420, color: '#10b981' },
  { name: 'DoS / DDoS', value: 480, color: '#ef4444' },
  { name: 'PortScan', value: 310, color: '#f59e0b' },
  { name: 'Web Attack (SQLi)', value: 165, color: '#f43f5e' },
  { name: 'Brute Force', value: 125, color: '#a855f7' },
  { name: 'Botnet', value: 75, color: '#06b6d4' },
];

export const MOCK_THREAT_CATEGORIES = [
  { category: 'DoS / DDoS', count: 480, riskScore: 95 },
  { category: 'PortScan', count: 310, riskScore: 65 },
  { category: 'SQL Injection', count: 165, riskScore: 90 },
  { category: 'SSH BruteForce', count: 125, riskScore: 78 },
  { category: 'Botnet C2', count: 75, riskScore: 88 },
];
